# .github/workflows/deploy-beta.yml

name: Deploy Beta to Firebase Hosting

on:
  push:
    branches:
      - develop  # Trigger this workflow on pushes to the 'develop' branch

jobs:
  build_and_deploy_beta:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Kiddo_Quest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Firebase CLI v14.11.0 requires Node.js 20+

      - name: Install Dependencies
        run: npm ci # 'ci' is generally faster and more reliable for CI environments

      - name: Run Tests
        run: npm test -- --watchAll=false --passWithNoTests # Run tests without coverage for speed

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: npm run test:e2e:minimal # Run minimal E2E tests for speed

      - name: Build Web App for Beta
        run: npm run build
        env:
          CI: false # Treat warnings as warnings, not errors

      - name: Deploy to Firebase Beta
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          projectId: 'kiddo-quest-de7b0'
          target: 'beta'
          entryPoint: './Kiddo_Quest'
          channelId: 'live'