name: Emergency Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - beta
      tag:
        description: 'Tag to rollback to (e.g., prod-deploy-20240115-143022)'
        required: true
        type: string
      reason:
        description: 'Reason for rollback'
        required: true
        type: string

env:
  NODE_VERSION: '18'
  WORKING_DIRECTORY: ./Kiddo_Quest

jobs:
  validate-rollback:
    name: Validate Rollback Request
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate tag exists
      run: |
        echo "🔍 Validating rollback tag: ${{ inputs.tag }}"
        git fetch --tags
        if git tag -l | grep -q "^${{ inputs.tag }}$"; then
          echo "✅ Tag ${{ inputs.tag }} found"
        else
          echo "❌ Tag ${{ inputs.tag }} not found"
          exit 1
        fi
    
    - name: Log rollback request
      run: |
        echo "🚨 ROLLBACK REQUEST"
        echo "Environment: ${{ inputs.environment }}"
        echo "Target Tag: ${{ inputs.tag }}"  
        echo "Reason: ${{ inputs.reason }}"
        echo "Requested by: ${{ github.actor }}"
        echo "Time: $(date)"

  rollback:
    name: Execute Rollback
    runs-on: ubuntu-latest
    needs: validate-rollback
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    environment:
      name: ${{ inputs.environment }}
    
    steps:
    - name: Checkout rollback target
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.tag }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build rollback version
      run: |
        if [ "${{ inputs.environment }}" = "production" ]; then
          cp .env.production .env
        else
          cp .env.beta .env
        fi
        npm run build
      env:
        CI: false
    
    - name: Deploy rollback to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: kiddo-quest-de7b0
        channelId: live
        target: ${{ inputs.environment }}
        entryPoint: ${{ env.WORKING_DIRECTORY }}
    
    - name: Verify rollback
      run: |
        sleep 30
        URL="${{ inputs.environment == 'production' && 'https://kiddo-quest-de7b0.web.app' || 'https://beta-kiddo-quest.web.app' }}"
        curl -f $URL || exit 1
        echo "✅ Rollback to ${{ inputs.tag }} completed successfully"
    
    - name: Create rollback tag
      run: |
        DATE=$(date +"%Y%m%d-%H%M%S")
        TAG="rollback-${{ inputs.environment }}-$DATE"
        git tag $TAG
        echo "🏷️ Created rollback tag: $TAG"